apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.auth.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.auth.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.auth.database }}
